# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='minuti',
            field=models.CharField(default='', max_length=100000000000),
        ),
    ]
