# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_minuti'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static'),
        ),
    ]
